#ifndef CONFIG_H
#define CONFIG_H

#include <cstdint>

#define SAMPLE_RATE 44100.0
#define LUT_SIZE 1024

#define M_2PI 6.28318530717958647692
#define TWO_PI_OVER_SAMPLE_RATE  (M_2PI / SAMPLE_RATE)
#define PARAM_LOWEST_VALUE 0.0001
#define PHASE_LUT_SCALE_FACTOR (LUT_SIZE / SAMPLE_RATE)
#define DRAWBARS_COUNT 9
#define MIDI_NOTES_COUNT 128
#define TONEWHEELS (91)
#define MANUAL_KEYS (61)
#define MANUAL_KEY_FIRST (36)
#define MANUAL_KEY_LAST (MANUAL_KEY_FIRST + MANUAL_KEYS)
#define MIN_AMPLITUDE 0
#define MAX_AMPLITUDE (0xFFFF / 2) // half of 16 bits
#define HEADROOM_SCALE_FACTOR (1.0 / DRAWBARS_COUNT / 3.0)
#define MAX_DRAWBAR_AMPLITUDE (MAX_AMPLITUDE * HEADROOM_SCALE_FACTOR)
#define MIN_DRAWBAR_AMPLITUDE (-MAX_DRAWBAR_AMPLITUDE)
#define INT8_TO_INT16_SCALE_FACTOR (0x7FFF / 0x7F)


#endif